sudo: false
language: node_js
node_js:
- 10
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_d068ddbe1a72_key -iv $encrypted_d068ddbe1a72_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- docker build -t mufdvr/github_interface .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
branches:
  only:
  - master
