sudo: false

language: node_js
node_js:
  - 10

services:
  - docker

before_install:
  - docker build -t mufdvr/github_interface .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

branches:
  only:
    - master